strip color from the output

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -33,7 +33,7 @@ runs:
           local COUNT
 
           # Run TSC and capture output
-          OUTPUT=$(npx tsc --pretty false --noEmit --strict --skipLibCheck 2>&1 || true)
+          OUTPUT=$(npx tsc --pretty --noEmit --strict --skipLibCheck 2>&1 || true)
 
           # Parse the error count from the lines that match any of these forms:
           # - "Found 1 error in {0}"
@@ -48,7 +48,7 @@ runs:
             COUNT=0
           fi
         
-          echo "$OUTPUT" > $RUNNER_TEMP/head_strict_errors.txt
+          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' > $RUNNER_TEMP/head_strict_errors.txt
           echo "$COUNT"
         }
 
@@ -94,7 +94,7 @@ runs:
           local COUNT
 
           # Run TSC and capture output
-          OUTPUT=$(npx tsc --pretty false --noEmit --strict --skipLibCheck 2>&1 || true)
+          OUTPUT=$(npx tsc --pretty --noEmit --strict --skipLibCheck 2>&1 || true)
 
           # Parse the error count from the lines that match any of these forms:
           # - "Found 1 error in {0}"
@@ -109,7 +109,7 @@ runs:
             COUNT=0
           fi
 
-          echo "$OUTPUT" > $RUNNER_TEMP/base_strict_errors.txt
+          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' > $RUNNER_TEMP/base_strict_errors.txt
           echo "$COUNT"
         }
 
